import type { ParsedResource, CloudProvider } from "../types/resources.js";
import type { CostEstimate, CostBreakdown } from "../types/pricing.js";
import type { CloudCostConfig } from "../types/config.js";
import type { PricingEngine } from "../pricing/pricing-engine.js";
import { calculateComputeCost } from "./compute.js";
import { calculateDatabaseCost } from "./database.js";
import { calculateStorageCost } from "./storage.js";
import { calculateNatGatewayCost, calculateLoadBalancerCost } from "./network.js";
import { calculateKubernetesCost } from "./kubernetes.js";
import {
  calculateLambdaCost,
  calculateDynamoDbCost,
  calculateSqsCost,
} from "./serverless.js";
import {
  calculateElastiCacheCost,
  calculateAzureRedisCacheCost,
  calculateGcpRedisCost,
  calculateCloudFrontCost,
} from "./cache.js";
import {
  calculateAppServicePlanCost,
  calculateCosmosDbCost,
  calculateAzureFunctionCost,
  calculateCloudRunCost,
  calculateBigQueryCost,
  calculateGcpFunctionCost,
} from "./paas.js";
import {
  calculateAwsDataTransferCost,
  calculateAzureDataTransferCost,
  calculateGcpDataTransferCost,
} from "./data-transfer.js";
import { calculateContainerRegistryCost } from "./container-registry.js";
import { calculateSecretsCost } from "./secrets.js";
import { calculateDnsCost } from "./dns.js";
import { logger } from "../logger.js";

// ---------------------------------------------------------------------------
// Resource type classification
// ---------------------------------------------------------------------------

const COMPUTE_TYPES = new Set([
  "aws_instance",
  "azurerm_linux_virtual_machine",
  "azurerm_windows_virtual_machine",
  "google_compute_instance",
  // Node groups – cost their compute like VMs.
  "aws_eks_node_group",
  "azurerm_kubernetes_cluster_node_pool",
  "google_container_node_pool",
  "compute_node",
]);

const DATABASE_TYPES = new Set([
  "aws_db_instance",
  "azurerm_postgresql_flexible_server",
  "azurerm_mysql_flexible_server",
  "azurerm_mssql_server",
  "google_sql_database_instance",
]);

const BLOCK_STORAGE_TYPES = new Set([
  "aws_ebs_volume",
  "azurerm_managed_disk",
  "google_compute_disk",
]);

const OBJECT_STORAGE_TYPES = new Set([
  "aws_s3_bucket",
  "azurerm_storage_account",
  "google_storage_bucket",
]);

const NAT_GATEWAY_TYPES = new Set([
  "aws_nat_gateway",
  "azurerm_nat_gateway",
  "google_compute_router_nat",
]);

const LOAD_BALANCER_TYPES = new Set([
  "aws_lb",
  "aws_alb",
  "azurerm_lb",
  "azurerm_application_gateway",
  "google_compute_forwarding_rule",
]);

const KUBERNETES_TYPES = new Set([
  "aws_eks_cluster",
  "azurerm_kubernetes_cluster",
  "google_container_cluster",
]);

// Synthetic resource types used internally to route data transfer cost
// calculations. These never appear in real Terraform configurations — they are
// generated by calculateBreakdown() based on which real resources were costed.
const DATA_TRANSFER_TYPES = new Set([
  "aws_data_transfer",
  "azurerm_data_transfer",
  "google_data_transfer",
]);

// Maps a CloudProvider to the synthetic resource type used for data transfer
// cost routing in calculateCost().
const DATA_TRANSFER_TYPE_FOR_PROVIDER: Record<string, string> = {
  aws: "aws_data_transfer",
  azure: "azurerm_data_transfer",
  gcp: "google_data_transfer",
};

// ---------------------------------------------------------------------------
// New resource type sets
// ---------------------------------------------------------------------------

const SERVERLESS_LAMBDA_TYPES = new Set([
  "aws_lambda_function",
]);

const SERVERLESS_DYNAMODB_TYPES = new Set([
  "aws_dynamodb_table",
]);

const SERVERLESS_SQS_TYPES = new Set([
  "aws_sqs_queue",
]);

const ELASTICACHE_TYPES = new Set([
  "aws_elasticache_cluster",
  "aws_elasticache_replication_group",
]);

const AZURE_REDIS_TYPES = new Set([
  "azurerm_redis_cache",
]);

const GCP_REDIS_TYPES = new Set([
  "google_redis_instance",
]);

const CLOUDFRONT_TYPES = new Set([
  "aws_cloudfront_distribution",
]);

const AZURE_APP_SERVICE_TYPES = new Set([
  "azurerm_app_service_plan",
]);

const AZURE_COSMOS_TYPES = new Set([
  "azurerm_cosmosdb_account",
]);

const AZURE_FUNCTION_TYPES = new Set([
  "azurerm_function_app",
  "azurerm_linux_function_app",
  "azurerm_windows_function_app",
]);

const CLOUD_RUN_TYPES = new Set([
  "google_cloud_run_service",
  "google_cloud_run_v2_service",
]);

const BIGQUERY_TYPES = new Set([
  "google_bigquery_dataset",
  "google_bigquery_table",
]);

const GCP_FUNCTION_TYPES = new Set([
  "google_cloudfunctions_function",
  "google_cloudfunctions2_function",
]);

const CONTAINER_REGISTRY_TYPES = new Set([
  "aws_ecr_repository",
  "azurerm_container_registry",
  "google_artifact_registry_repository",
]);

const SECRETS_TYPES = new Set([
  "aws_secretsmanager_secret",
  "azurerm_key_vault",
  "google_secret_manager_secret",
]);

const DNS_TYPES = new Set([
  "aws_route53_zone",
  "azurerm_dns_zone",
  "google_dns_managed_zone",
]);

// ---------------------------------------------------------------------------
// Service label helper (for by_service aggregation)
// ---------------------------------------------------------------------------

function serviceLabel(resourceType: string): string {
  if (COMPUTE_TYPES.has(resourceType)) return "compute";
  if (DATABASE_TYPES.has(resourceType)) return "database";
  if (BLOCK_STORAGE_TYPES.has(resourceType)) return "block_storage";
  if (OBJECT_STORAGE_TYPES.has(resourceType)) return "object_storage";
  if (NAT_GATEWAY_TYPES.has(resourceType)) return "network";
  if (LOAD_BALANCER_TYPES.has(resourceType)) return "network";
  if (KUBERNETES_TYPES.has(resourceType)) return "kubernetes";
  if (SERVERLESS_LAMBDA_TYPES.has(resourceType)) return "serverless";
  if (SERVERLESS_DYNAMODB_TYPES.has(resourceType)) return "serverless";
  if (SERVERLESS_SQS_TYPES.has(resourceType)) return "serverless";
  if (ELASTICACHE_TYPES.has(resourceType)) return "cache";
  if (AZURE_REDIS_TYPES.has(resourceType)) return "cache";
  if (GCP_REDIS_TYPES.has(resourceType)) return "cache";
  if (CLOUDFRONT_TYPES.has(resourceType)) return "cdn";
  if (AZURE_APP_SERVICE_TYPES.has(resourceType)) return "paas";
  if (AZURE_COSMOS_TYPES.has(resourceType)) return "database";
  if (AZURE_FUNCTION_TYPES.has(resourceType)) return "serverless";
  if (CLOUD_RUN_TYPES.has(resourceType)) return "serverless";
  if (BIGQUERY_TYPES.has(resourceType)) return "analytics";
  if (GCP_FUNCTION_TYPES.has(resourceType)) return "serverless";
  if (DATA_TRANSFER_TYPES.has(resourceType)) return "data_transfer";
  if (CONTAINER_REGISTRY_TYPES.has(resourceType)) return "container_registry";
  if (SECRETS_TYPES.has(resourceType)) return "secrets";
  if (DNS_TYPES.has(resourceType)) return "dns";
  return "other";
}

// ---------------------------------------------------------------------------
// CostEngine
// ---------------------------------------------------------------------------

/**
 * CostEngine is the top-level orchestrator for multi-cloud cost estimation.
 *
 * It dispatches each ParsedResource to the appropriate sub-calculator based on
 * resource type, collects the resulting CostEstimate objects, and aggregates
 * them into a CostBreakdown with per-service totals.
 */
export class CostEngine {
  private pricingEngine: PricingEngine;
  private monthlyHours: number;
  private config: CloudCostConfig;

  constructor(pricingEngine: PricingEngine, config: CloudCostConfig) {
    this.pricingEngine = pricingEngine;
    this.monthlyHours = config.pricing.monthly_hours;
    this.config = config;
  }

  /**
   * Calculates the cost of a single resource on a target provider.
   */
  async calculateCost(
    resource: ParsedResource,
    targetProvider: CloudProvider,
    targetRegion: string
  ): Promise<CostEstimate> {
    const type = resource.type;

    logger.debug("CostEngine.calculateCost", {
      resourceId: resource.id,
      type,
      targetProvider,
      targetRegion,
    });

    if (COMPUTE_TYPES.has(type)) {
      return calculateComputeCost(
        resource,
        targetProvider,
        targetRegion,
        this.pricingEngine,
        this.monthlyHours,
        this.config.pricing
      );
    }

    if (DATABASE_TYPES.has(type)) {
      return calculateDatabaseCost(
        resource,
        targetProvider,
        targetRegion,
        this.pricingEngine,
        this.monthlyHours
      );
    }

    if (BLOCK_STORAGE_TYPES.has(type) || OBJECT_STORAGE_TYPES.has(type)) {
      return calculateStorageCost(
        resource,
        targetProvider,
        targetRegion,
        this.pricingEngine
      );
    }

    if (NAT_GATEWAY_TYPES.has(type)) {
      return calculateNatGatewayCost(
        resource,
        targetProvider,
        targetRegion,
        this.pricingEngine,
        this.monthlyHours
      );
    }

    if (LOAD_BALANCER_TYPES.has(type)) {
      return calculateLoadBalancerCost(
        resource,
        targetProvider,
        targetRegion,
        this.pricingEngine,
        this.monthlyHours
      );
    }

    if (KUBERNETES_TYPES.has(type)) {
      return calculateKubernetesCost(
        resource,
        targetProvider,
        targetRegion,
        this.pricingEngine,
        this.monthlyHours
      );
    }

    // ------------------------------------------------------------------
    // Serverless
    // ------------------------------------------------------------------

    if (SERVERLESS_LAMBDA_TYPES.has(type)) {
      return calculateLambdaCost(resource, targetProvider, targetRegion);
    }

    if (SERVERLESS_DYNAMODB_TYPES.has(type)) {
      return calculateDynamoDbCost(resource, targetProvider, targetRegion);
    }

    if (SERVERLESS_SQS_TYPES.has(type)) {
      return calculateSqsCost(resource, targetProvider, targetRegion);
    }

    // ------------------------------------------------------------------
    // Cache / CDN
    // ------------------------------------------------------------------

    if (ELASTICACHE_TYPES.has(type)) {
      return calculateElastiCacheCost(resource, targetProvider, targetRegion);
    }

    if (AZURE_REDIS_TYPES.has(type)) {
      return calculateAzureRedisCacheCost(resource, targetProvider, targetRegion);
    }

    if (GCP_REDIS_TYPES.has(type)) {
      return calculateGcpRedisCost(resource, targetProvider, targetRegion);
    }

    if (CLOUDFRONT_TYPES.has(type)) {
      return calculateCloudFrontCost(resource, targetProvider, targetRegion);
    }

    // ------------------------------------------------------------------
    // PaaS / Analytics
    // ------------------------------------------------------------------

    if (AZURE_APP_SERVICE_TYPES.has(type)) {
      return calculateAppServicePlanCost(resource, targetProvider, targetRegion);
    }

    if (AZURE_COSMOS_TYPES.has(type)) {
      return calculateCosmosDbCost(resource, targetProvider, targetRegion);
    }

    if (AZURE_FUNCTION_TYPES.has(type)) {
      return calculateAzureFunctionCost(resource, targetProvider, targetRegion);
    }

    if (CLOUD_RUN_TYPES.has(type)) {
      return calculateCloudRunCost(resource, targetProvider, targetRegion);
    }

    if (BIGQUERY_TYPES.has(type)) {
      return calculateBigQueryCost(resource, targetProvider, targetRegion);
    }

    if (GCP_FUNCTION_TYPES.has(type)) {
      return calculateGcpFunctionCost(resource, targetProvider, targetRegion);
    }

    // ------------------------------------------------------------------
    // Data transfer
    // ------------------------------------------------------------------

    if (type === "aws_data_transfer") {
      return calculateAwsDataTransferCost(resource, targetRegion);
    }

    if (type === "azurerm_data_transfer") {
      return calculateAzureDataTransferCost(resource, targetRegion);
    }

    if (type === "google_data_transfer") {
      return calculateGcpDataTransferCost(resource, targetRegion);
    }

    // ------------------------------------------------------------------
    // Container registry / Secrets / DNS
    // ------------------------------------------------------------------

    if (CONTAINER_REGISTRY_TYPES.has(type)) {
      return calculateContainerRegistryCost(resource, targetProvider, targetRegion);
    }

    if (SECRETS_TYPES.has(type)) {
      return calculateSecretsCost(resource, targetProvider, targetRegion);
    }

    if (DNS_TYPES.has(type)) {
      return calculateDnsCost(resource, targetProvider, targetRegion);
    }

    // Unsupported resource type – return a zero-cost estimate so callers can
    // still include it in the breakdown without crashing.
    logger.warn("CostEngine: unsupported resource type", { type, targetProvider });
    return {
      resource_id: resource.id,
      resource_type: type,
      resource_name: resource.name,
      provider: targetProvider,
      region: targetRegion,
      monthly_cost: 0,
      yearly_cost: 0,
      currency: "USD",
      breakdown: [],
      confidence: "low",
      notes: [`Resource type "${type}" is not yet supported by the cost engine`],
      pricing_source: "fallback" as const,
    };
  }

  /**
   * Calculates costs for all resources and aggregates them into a CostBreakdown.
   *
   * Resources that fail to produce a cost estimate are logged and skipped rather
   * than letting a single failure abort the entire calculation.
   *
   * When include_data_transfer is enabled (the default), a synthetic data
   * transfer line item is appended for each unique provider+region combination
   * present in the successfully costed resources. This provides a baseline
   * egress cost estimate without requiring explicit data transfer resources in
   * the Terraform configuration.
   */
  async calculateBreakdown(
    resources: ParsedResource[],
    targetProvider: CloudProvider,
    targetRegion: string
  ): Promise<CostBreakdown> {
    const estimates: CostEstimate[] = [];
    const byService: Record<string, number> = {};
    const warnings: string[] = [];

    // Fan out all resource cost calculations concurrently. Promise.allSettled()
    // ensures a single pricing fetch failure never aborts the entire breakdown —
    // rejected promises are logged and silently dropped.
    const resourceResults = await Promise.allSettled(
      resources.map((resource) =>
        this.calculateCost(resource, targetProvider, targetRegion).then(
          (estimate) => ({ resource, estimate })
        )
      )
    );

    for (const result of resourceResults) {
      if (result.status === "rejected") {
        logger.error("CostEngine: failed to calculate cost for resource", {
          error: result.reason instanceof Error ? result.reason.message : String(result.reason),
        });
        continue;
      }

      const { resource, estimate } = result.value;
      estimates.push(estimate);

      const svc = serviceLabel(resource.type);
      byService[svc] = (byService[svc] ?? 0) + estimate.monthly_cost;

      // Surface warnings for fallback pricing and missing data.
      if (estimate.pricing_source === "fallback") {
        warnings.push(
          `${estimate.resource_name} (${estimate.resource_type}): using fallback/bundled pricing data`
        );
      }
      if (estimate.monthly_cost === 0 && estimate.confidence === "low") {
        warnings.push(
          `No pricing data found for ${estimate.resource_type} in ${targetRegion} — cost reported as $0`
        );
      }
    }

    // Append data transfer line items when enabled and at least one real
    // resource was successfully costed. One synthetic resource is created per
    // unique provider+region combination so the breakdown always surfaces an
    // egress cost estimate alongside the infrastructure costs.
    if (this.config.pricing.include_data_transfer && estimates.length > 0) {
      const seenProviderRegions = new Set<string>();
      const syntheticResources: Array<{ resource: ParsedResource; dtResourceType: string }> = [];

      for (const estimate of estimates) {
        // Skip estimates that were themselves produced by synthetic data
        // transfer resources to avoid double-counting.
        if (DATA_TRANSFER_TYPES.has(estimate.resource_type)) continue;

        const key = `${estimate.provider}::${estimate.region}`;
        if (seenProviderRegions.has(key)) continue;
        seenProviderRegions.add(key);

        const dtResourceType = DATA_TRANSFER_TYPE_FOR_PROVIDER[estimate.provider];
        if (!dtResourceType) continue;

        syntheticResources.push({
          dtResourceType,
          resource: {
            id: `synthetic-data-transfer-${estimate.provider}-${estimate.region}`,
            type: dtResourceType,
            name: `data-transfer-${estimate.provider}-${estimate.region}`,
            provider: estimate.provider,
            region: estimate.region,
            attributes: { monthly_egress_gb: 100 },
            tags: {},
            source_file: "synthetic",
          },
        });
      }

      // Fan out all data transfer calculations concurrently.
      const dtResults = await Promise.allSettled(
        syntheticResources.map(({ resource, dtResourceType }) =>
          this.calculateCost(resource, resource.provider, resource.region).then(
            (dtEstimate) => ({ dtEstimate, dtResourceType })
          )
        )
      );

      for (const result of dtResults) {
        if (result.status === "rejected") {
          logger.error("CostEngine: failed to calculate data transfer cost", {
            error: result.reason instanceof Error ? result.reason.message : String(result.reason),
          });
          continue;
        }

        const { dtEstimate, dtResourceType } = result.value;
        estimates.push(dtEstimate);

        const svc = serviceLabel(dtResourceType);
        byService[svc] = (byService[svc] ?? 0) + dtEstimate.monthly_cost;
      }
    }

    const totalMonthly = estimates.reduce((sum, e) => sum + e.monthly_cost, 0);

    const budgetWarnings = this.evaluateBudget(totalMonthly, estimates);

    return {
      provider: targetProvider,
      region: targetRegion,
      total_monthly: Math.round(totalMonthly * 100) / 100,
      total_yearly: Math.round(totalMonthly * 12 * 100) / 100,
      currency: "USD",
      by_service: Object.fromEntries(
        Object.entries(byService).map(([k, v]) => [k, Math.round(v * 100) / 100])
      ),
      by_resource: estimates,
      generated_at: new Date().toISOString(),
      warnings,
      ...(budgetWarnings.length > 0 && { budget_warnings: budgetWarnings }),
    };
  }

  /**
   * Evaluates configured budget thresholds against the computed totals and
   * per-resource costs. Returns an array of human-readable warning strings —
   * empty when no budget is configured or no thresholds are breached.
   */
  private evaluateBudget(totalMonthly: number, estimates: CostEstimate[]): string[] {
    const budget = this.config.budget;
    if (!budget) return [];

    const warnPct = budget.warn_percentage ?? 80;
    const budgetWarnings: string[] = [];

    if (budget.monthly_limit !== undefined) {
      const limit = budget.monthly_limit;
      const roundedTotal = Math.round(totalMonthly * 100) / 100;

      if (totalMonthly > limit) {
        const overage = Math.round((totalMonthly - limit) * 100) / 100;
        const pct = Math.round((totalMonthly / limit) * 100);
        budgetWarnings.push(
          `BUDGET EXCEEDED: Monthly cost $${roundedTotal} exceeds limit of $${limit} by $${overage} (${pct}%)`
        );
      } else if (totalMonthly > limit * (warnPct / 100)) {
        const pct = Math.round((totalMonthly / limit) * 100);
        budgetWarnings.push(
          `BUDGET WARNING: Monthly cost $${roundedTotal} is at ${pct}% of $${limit} limit`
        );
      }
    }

    if (budget.per_resource_limit !== undefined) {
      const limit = budget.per_resource_limit;
      for (const estimate of estimates) {
        if (estimate.monthly_cost > limit) {
          const roundedCost = Math.round(estimate.monthly_cost * 100) / 100;
          budgetWarnings.push(
            `RESOURCE OVER BUDGET: ${estimate.resource_id} costs $${roundedCost}/month, exceeds per-resource limit of $${limit}`
          );
        }
      }
    }

    return budgetWarnings;
  }
}
